site_name: OmniBox Documentation
site_description: Instructions for printing and assembly the OmniBox.
site_author: Jon Harper
site_url: https://jon-harper.github.io/OmniBox
repo_url: https://github.com/jon-harper/OmniBox

theme:
  name: material
  # name: bootstrap4

markdown_extensions:
  - admonition

nav:
  - index.md
  - gallery.md
  - Supported Parts:
    - support.md
    - boards.md
    - displays.md
    - panel_mounts.md
    - fans.md
    - lower_bay.md
  - bom.md
  - printing.md
  - Assembly:
    - assembly/index.md
    - assembly/core.md
    - assembly/trays.md
    - assembly/panels.md
  