site_name: OmniBox Documentation
site_description: Instructions for printing and assembly the OmniBox.
site_author: Jon Harper
site_url: https://jon-harper.github.io/OmniBox
repo_url: https://github.com/jon-harper/OmniBox
repo_name: jon-harper/OmniBox
edit_uri: ""

theme:
  name: material
  icon:
    logo: material/book-open-variant
  features:
    - navigation.instant
    - navigation.sections
    - navigation.top
    
  font:
    text: Noto Sans
    code: Source Code Pro
  palette: 
    - scheme: default
      primary: teal
      accent: deep orange
      toggle:
        icon: material/lightbulb-on
        name: Switch to dark mode
    - scheme: slate
      primary: deep orange
      accent: teal
      toggle:
        icon: material/lightbulb-off-outline
        name: Switch to light mode

markdown_extensions:
  - admonition
  - attr_list
  - abbr
  - md_in_html
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.snippets:
      auto_append: 
        - include/links.md
  - pymdownx.tabbed:
      alternate_style: true 
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
      
nav:
  - index.md
  - development.md
  - tour.md
  - Requirements:
    - printing.md
    - bom.md
  - Supported Parts:
    - support/index.md
    - support/boards.md
    - support/displays.md
    - support/panel_mounts.md
    - support/fans.md
    - support/lower_bay.md
  - Assembly Guide:
    - assembly/index.md
    - assembly/core.md
    - assembly/trays.md
    - assembly/panels.md
  - Version History:
    - history/index.md
    - history/v0.9.8.1.md
    - history/v0.9.8.md
    - history/v0.9.7.md
    - history/v0.9.5.md
    - history/v0.9.md
  