site_name: OmniBox Documentation
site_description: Instructions for printing and assembly the OmniBox.
site_author: Jon Harper
site_url: https://jon-harper.github.io/OmniBox
repo_url: https://github.com/jon-harper/OmniBox

theme:
  name: material
  
markdown_extensions:
  - admonition

nav:
  - index.md
  - gallery.md
  - Supported Parts:
    - support/index.md
    - support/boards.md
    - support/displays.md
    - support/panel_mounts.md
    - support/fans.md
    - support/lower_bay.md
  - bom.md
  - printing.md
  - Assembly:
    - assembly/index.md
    - assembly/core.md
    - assembly/trays.md
    - assembly/panels.md
  